# Generated by Django 3.2.17 on 2023-02-05 21:23

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200, unique=True)),
                ('mainbody', djrichtextfield.models.RichTextField(blank=True, max_length=5000, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csiblog_comment', to='csiblog.post')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
