# Generated by Django 3.2.17 on 2023-07-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0003_alter_comment_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csiblog_comment', to='csiblog.post'),
        ),
    ]
