# Generated by Django 3.2.17 on 2023-02-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0004_auto_20230205_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
