# Generated by Django 3.2.17 on 2023-02-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0008_auto_20230205_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
