# Generated by Django 3.2.17 on 2023-02-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0009_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
