# Generated by Django 3.2.17 on 2023-02-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0010_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
