# Generated by Django 3.2.17 on 2023-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0012_auto_20230215_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='catname',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=150),
        ),
    ]
