# Generated by Django 3.2.17 on 2023-02-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0013_auto_20230215_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='comment',
            name='catname',
            field=models.CharField(default=1, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='catname',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
