# Generated by Django 3.2.17 on 2023-02-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0014_auto_20230215_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='catname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='catname',
        ),
    ]
