# Generated by Django 3.2.17 on 2023-02-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0015_auto_20230216_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
