# Generated by Django 3.2.17 on 2023-02-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0017_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
