# Generated by Django 3.2.17 on 2023-02-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0018_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
