# Generated by Django 3.2.17 on 2023-02-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0019_auto_20230220_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
