# Generated by Django 3.2.17 on 2023-02-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0020_auto_20230221_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csiblog_posts', to='csiblog.post'),
        ),
    ]
