# Generated by Django 3.2.17 on 2023-02-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csiblog', '0026_auto_20230226_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
